print("#/=========================================/")
print("#/                                         /")
print("#/             Program halo.py             /")
print("#/  by anggoro.eko.nugroho@mail.ugm.ac.id  /")
print("#/                                         /")
print("#/=========================================/")
